# .travis.yml
#
# Replaced wp-cli version with
# https://stevegrunwell.com/blog/travis-ci-wordpress-plugins/

language: php
 
services:
  - mysql
 
cache:
  directories:
    - $HOME/.composer/cache
 
# Explicitly test against supported versions of PHP
#
# Reference: https://www.php.net/supported-versions.php
php:
  - 7.4 # until 28 Nov 2022
  - 7.3 # until  6 Dec 2021
  - 7.2 # until 30 Nov 2020

# Test against the latest version of WordPress and one version back.
env:
  - WP_VERSION=latest
  - WP_VERSION=5.3

# Customize the build matrix.
matrix:
  fast_finish: true
  include:

    # Run PHP_CodeSniffer
    - name: Coding standards
      php: 7.3
      env: WP_VERSION=latest WP_TRAVISCI=phpcs

    # Canary for our oldest-supported version
    - name: Legacy
      php: 5.6
      env: WP_VERSION=4.9
 
    # Nightly versions of PHP and WordPress.
    - name: Bleeding edge
      # PHP nightly has moved to 8.0.0 which breaks many things.
      # php: nightly
      php: 7.4
      env: WP_VERSION=trunk

  # Jobs that are permitted to fail without breaking the build
  allow_failures:
    - name: Bleeding edge

before_install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
 
  # Unless we need XDebug, disable it for improved performance.
  - phpenv config-rm xdebug.ini || return 0

install:

  # Install an older version of PHPUnit if we can't support v7.
  - |
    if [[ "$TRAVIS_PHP_VERSION" < "7.2" ]]; then
      composer remove phpunit/phpunit --no-update --dev
    fi

  # Run Composer
  - composer update 

  # Install our Composer dependencies
  - composer install --no-interaction

  # Install an older version of PHPUnit if we can't support v7.
  - |
    if [[ "$TRAVIS_PHP_VERSION" < "7.2" ]]; then
      wget -O ./vendor/bin/phpunit https://phar.phpunit.de/phpunit-5.phar
      chmod +x ./vendor/bin/phpunit
    fi

  # Install the WordPress core test suite
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - |
    # If we've set the $WP_TRAVISCI variable to run PHPCS, do that instead
    # of running PHPUnit.
    if [[ "$WP_TRAVISCI" == "phpcs" ]]; then
      ./vendor/bin/phpcs --config-set installed_paths ~/.composer/vendor/wp-coding-standards/wpcs
      ./vendor/bin/phpcs

    else
      # Execute the test suite
      ./vendor/bin/phpunit
 
      # Optionally run the tests again in a multisite environment
      #WP_MULTISITE=1 ./vendor/bin/phpunit
    fi
  # Show the actual WP version at the end.
  - grep "wp_version =" "/tmp/wordpress/wp-includes/version.php"
